name: flutter_rotation_sensor_example
description: "Demonstrates how to use the flutter_rotation_sensor plugin."
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rotation_sensor:
    path: ../
  simple_3d: 13.3.0
  simple_3d_renderer: ^19.1.0
  util_simple_3d: any

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - 'assets/images/top.png'
    - 'assets/images/other.png'
