version: 2
updates:

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "gradle"
    directory: "/example/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
