name: flutter_rotation_sensor
description: >
  A package provides a stream of device's orientation in three different representations: a rotation
  matrix, a quaternion, and Euler angles (azimuth, pitch, roll).
version: 0.1.0
repository: https://github.com/tlserver/flutter_rotation_sensor

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

topics:
  - rotation
  - orientation
  - heading
  - sensor
  - compass

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  # flutter_test depends on meta, so use any
  meta: any
  native_device_orientation: ^2.0.3
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  mockito: ^5.4.4

flutter:
  plugin:
    platforms:
      android:
        package: net.tlserver6y.flutter_rotation_sensor
        pluginClass: FlutterRotationSensorPlugin
      ios:
        pluginClass: FlutterRotationSensorPlugin
