name: Bug Report
description: File a report if you've encountered a bug with FlutterRotationSensor.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        # 🐛 Bug Report

        Thank you for using FlutterRotationSensor! Before you submit your bug report, please:

        - Review the [documentation](https://pub.dev/documentation/flutter_map_location_marker/latest/).
        - Search for similar issues in both [open and closed tickets](https://github.com/tlserver/flutter_rotation_sensor/issues?q=is%3Aissue).
        - Discuss non-bug-related questions on [GitHub discussions](https://github.com/tlserver/flutter_rotation_sensor/discussions) or [Stack Overflow](https://stackoverflow.com/).

        If you're certain the issue you're experiencing is a bug, please provide as much detail as possible in this report so we can help you resolve it.

        **Note:** Bug reports not adhering to this template may be closed for incomplete information.

  - type: checkboxes
    id: self-checks
    attributes:
      label: Preliminary Bug Check
      description: Ensure you've taken these steps before submitting a bug.
      options:
        - label: I've searched the issue tracker for similar bug reports.
          required: true
        - label: I've checked Google and Stack Overflow for solutions.
          required: true
        - label: I've read the plugin's documentation.
          required: true
        - label: I'm using the latest plugin version and all dependencies are updated with `flutter pub upgrade`.
          required: true
        - label: I've executed `flutter clean`.
          required: true
        - label: I've tried running the example project.
          required: true

  - type: input
    id: version
    attributes:
      label: Plugin Version
      description: What version of the plugin are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Please include as much detail as possible.
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      render: dart
      description: |
        Provide a minimal code sample or a link to a gist that reproduces the error. Ideally, share a main.dart file that we can run to see the issue.
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detail the exact steps to reproduce the bug.
    validations:
      required: true

  - type: input
    id: platform
    attributes:
      label: Platform Details
      description: Which platform and version did the issue occur on (e.g., Android, iOS)?
      placeholder: e.g., Android 12, iOS 14
    validations:
      required: true

  - type: input
    id: sdk
    attributes:
      label: Flutter SDK Version
      description: Provide the version of the Flutter SDK you are using.
      placeholder: e.g., 3.0.0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell
      description: |
        Attach the full output of `flutter run --verbose`. If there's an exception, ensure the log includes enough detail to diagnose the issue.
    validations:
      required: true

  - type: textarea
    id: doctor
    attributes:
      label: Flutter Doctor Output
      render: shell
      description: What is the output of `flutter doctor -v`? This provides us with your development environment details.
    validations:
      required: true